---
title: "Overview and Trends"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(tidyverse)
library(d3heatmap)
knitr::opts_chunk$set(echo = TRUE)
```
<p>
</br>
</p>

## Project overview
<head>  
  <style>  
    p { text-indent: 2.0em;}  
  </style>  
</head>
<p>
We limited our data to taxis going into Manhattan due to the size of the data available. Our logic is that this also reflects the general habits of New Yorkers, as most of the main attractions of New York City reside in the borough of Manhattan. We have made graphical representations, such as [heatmaps](heatmaps.html), [time distribution graphs](timedist.html) and inferences on [congestion](congestion.html) to help illustrate where people are going and how far they are willing to travel for a night out on Valentine's Day.
<head>  
  <style>  
    p { text-indent: 2.0em;}  
  </style>  
</head>
<p>
Upon an exploratory analysis of the dataset, we found that there were few rides coming from Staten Island into Manhattan. Therefore, we decided to focus on the other four boroughs for analysis, since there was not enough data from Staten Island to come up with meaningful interpretations.
</p>



