---
title: "Congestion"
author: "James Ng"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(tidyverse)
library(d3heatmap)
knitr::opts_chunk$set(echo = TRUE)
```


## General Trends

```{r ,echo = FALSE, warning = FALSE, message=FALSE}
vday_green_taxi <- read_csv("./data/vday_green_taxi.csv")
vday_yellow_taxi <- read_csv("./data/vday_yellow_taxi.csv")
vday_for_hire_vehicle <- read_csv("./data/vday_for_hire_vehicle.csv")

vday_for_hire_vehicle <- vday_for_hire_vehicle %>% 
  filter(hvfhs_license_num %in% c("HV0003", "HV0005"))

yellow_taxi_vday_samp <- sample_frac(vday_yellow_taxi, size = 0.1) %>% 
  mutate(type = "yellow")
green_taxi_vday_samp <- sample_frac(vday_green_taxi, size = 0.2) %>% 
  mutate(type = "green")
for_hire_vday_samp <- sample_frac(vday_for_hire_vehicle, size = 0.1) %>% 
  mutate(type = "for hire")

zone = read_csv("./data/taxi_zones.csv")

transport = bind_rows(yellow_taxi_vday_samp, green_taxi_vday_samp, for_hire_vday_samp) 

transport_final = left_join(transport, zone, by = c("pu_location_id" = "zone_id")) %>% 
  rename(pu_neighborhood = zone,
         pu_boro = borough) %>% 
  left_join(., zone, 
            by = c("do_location_id" = "zone_id")) %>%
  rename(do_neighborhood = zone,
         do_boro = borough) %>% 
  select(-ends_with("location_id")) %>% 
  filter(do_boro == "Manhattan") %>% 
  mutate(
  pu_time = paste(pickup_date, pickup_time, sep = " "),
  do_time = paste(dropoff_date, dropoff_time, sep = " "),
  duration = as.numeric(difftime(do_time, pu_time, units = "mins"))
) %>% 
  select(-do_time, -pu_time, -do_boro)

congestion_data = transport_final %>% 
  filter(total_amount>0) %>% 
  separate(pickup_time, into = c("pickup_hr", "pickup_min", "pickup_sec"), sep = ":") %>% 
  separate(dropoff_time, into = c("dropoff_hr", "dropoff_min", "dropoff_sec"), sep = ":") %>%  
  mutate(
    pickup_hr = as.numeric(pickup_hr),
    pickup_min = as.numeric(pickup_min),
    dropoff_hr = as.numeric(dropoff_hr),
    dropoff_min = as.numeric(dropoff_min)
  ) %>% 
  mutate(
    congestion = (fare_amount - (trip_distance*2.5) -2.5)/.5, 
    wait_pct = congestion/duration
  ) %>% 
  filter(ratecode_id==1) %>% 
  filter(wait_pct<1) %>% 
  filter(congestion>=0)

```

```{r ,echo = FALSE, warning = FALSE, message=FALSE}
congestion_data %>%  
  group_by(pickup_hr, pu_boro) %>%
  filter(pu_boro != "NA", pu_boro != "Staten Island") %>% 
  summarize(avg_cong = mean(wait_pct)) %>% 
  ggplot(aes(x=pickup_hr, y = avg_cong))+
    geom_line()+
  facet_grid(~pu_boro)+
  geom_smooth(method = lm)+
  labs(
    title = "Average Duration of your Trip Stuck in Traffic When Traveling to Manhattan")+
    xlab("Pick Up Hour")+
    ylab("Average Congestion of Travel")
```

<p>

The trends show that congestion in manhattan is pretty consistent whereas it fluctuates more in the other boroughs when traveling into manhattan. 

</p>

```{r ,echo = FALSE, warning = FALSE, message=FALSE}
congestion_matrix <- function(input_boro) {
  congestion_map = congestion_data %>% 
  filter(pu_boro == input_boro) %>%
  group_by(pu_neighborhood, do_neighborhood) %>%  
  summarize(avg_congestion = mean(congestion),
            avg_wait_pct = mean(wait_pct)) %>% 
    arrange(do_neighborhood) %>% 
  select(pu_neighborhood, do_neighborhood, avg_wait_pct) %>% 
  pivot_wider(
    names_from = pu_neighborhood,
    values_from = avg_wait_pct
  ) %>% 
  replace(is.na(.),0) %>% 
  arrange(do_neighborhood) 
    
man_man_congestion_matrix <- as.matrix(congestion_map[-1])
row.names(man_man_congestion_matrix) <- pull(congestion_map, do_neighborhood)  
return(man_man_congestion_matrix)  
}

heatmap_function <- function(input_matrix) {
  into_man_heatmap <- d3heatmap(input_matrix, scale = "none", colors = "RdPu",  dendrogram = "none", Rowv = FALSE, Colv = FALSE) 
  return(into_man_heatmap)
}
```

## Manhattan to Manhattan 
```{r ,echo = FALSE, warning = FALSE, message=FALSE}
man_man_congestion_matrix <- congestion_matrix("Manhattan")

heatmap_function(man_man_congestion_matrix)
```
 
<p>
From this heatmap, you can see that the average congestion in manhattan
</p>