---
title: "Heatmaps"
author: "Data Science Group 31 - Ngoc Duong, Sabrina Lin, James Ng, Adeline Shin"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(tidyverse)
library(d3heatmap)
knitr::opts_chunk$set(echo = TRUE)
```

## Heatmaps

```{r ,echo=FALSE, warning=FALSE, message=FALSE}
vday_green_taxi <- read_csv("./data/vday_green_taxi.csv")
vday_yellow_taxi <- read_csv("./data/vday_yellow_taxi.csv")
vday_for_hire_vehicle <- read_csv("./data/vday_for_hire_vehicle.csv")

vday_for_hire_vehicle <- vday_for_hire_vehicle %>% 
  filter(hvfhs_license_num %in% c("HV0003", "HV0005"))

yellow_taxi_vday_samp <- sample_frac(vday_yellow_taxi, size = 0.1) %>% 
  mutate(type = "yellow")
green_taxi_vday_samp <- sample_frac(vday_green_taxi, size = 0.2) %>% 
  mutate(type = "green")
for_hire_vday_samp <- sample_frac(vday_for_hire_vehicle, size = 0.1) %>% 
  mutate(type = "for hire")

zone = read_csv("./data/taxi_zones.csv")

transport = bind_rows(yellow_taxi_vday_samp, green_taxi_vday_samp, for_hire_vday_samp) 

transport_final = left_join(transport, zone, by = c("pu_location_id" = "zone_id")) %>% 
  rename(pu_neighborhood = zone,
         pu_boro = borough) %>% 
  left_join(., zone, 
            by = c("do_location_id" = "zone_id")) %>%
  rename(do_neighborhood = zone,
         do_boro = borough) %>% 
  select(-ends_with("location_id")) %>% 
  filter(do_boro == "Manhattan") %>% 
  mutate(
  pu_time = paste(pickup_date, pickup_time, sep = " "),
  do_time = paste(dropoff_date, dropoff_time, sep = " "),
  duration = as.numeric(difftime(do_time, pu_time, units = "mins"))
) %>% 
  select(-do_time, -pu_time, -do_boro)

dinner_time_transport <- transport_final %>% 
  filter(stringr::str_detect(pickup_time, '^18|^19|^20'))

late_night_transport <- transport_final %>% 
  filter(
    stringr::str_detect(pickup_time, '^21|^22|^23')|
    pickup_date == "2019-02-15"
    )
```


```{r heatmap codes,echo=FALSE,warning=FALSE,message=FALSE}
manhattan_matrix <- function(input_boro, input_df) {
  man_man_df <- input_df %>% 
  filter(
    pu_boro == input_boro
  ) %>% 
  select(
    pu_neighborhood, do_neighborhood
  ) %>% 
  group_by(pu_neighborhood, do_neighborhood) %>% 
  summarise(count = n()) %>% 
  pivot_wider(
    names_from = pu_neighborhood,
    values_from = count
  ) %>% 
  replace(is.na(.),0) %>% 
  arrange(do_neighborhood) 

man_man_matrix <- as.matrix(man_man_df[-1])
row.names(man_man_matrix) <- pull(man_man_df, do_neighborhood)  
return(man_man_matrix)
}

heatmap_function <- function(input_matrix) {
  into_man_heatmap <- d3heatmap(input_matrix, scale = "none", colors = "RdPu",  dendrogram = "none", Rowv = FALSE, Colv = FALSE) 
  return(into_man_heatmap)
}
```

## Manhattan to Manhattan

```{r ,echo=FALSE, warning=FALSE, message=FALSE}
man_man_matrix <- manhattan_matrix("Manhattan", transport_final)

heatmap_function(man_man_matrix)
```


## Brooklyn to Manhattan

```{r ,echo=FALSE, warning=FALSE, message=FALSE}
brooklyn_man_matrix <- manhattan_matrix("Brooklyn", transport_final)

heatmap_function(brooklyn_man_matrix)
```

## Queens to Manhattan

```{r ,echo=FALSE, warning=FALSE, message=FALSE}
queens_man_matrix <- manhattan_matrix("Queens", transport_final)

heatmap_function(queens_man_matrix)
```

## Bronx to Manhattan

```{r ,echo=FALSE, warning=FALSE, message=FALSE}
bronx_man_matrix <- manhattan_matrix("Bronx", transport_final) 

heatmap_function(bronx_man_matrix)
```

# Dinner time Valentine's Day

## Manhattan to Manhattan

```{r ,echo=FALSE, warning=FALSE, message=FALSE}
man_man_dinner <- manhattan_matrix("Manhattan", dinner_time_transport)

heatmap_function(man_man_dinner)
```


## Brooklyn to Manhattan

```{r ,echo=FALSE, warning=FALSE, message=FALSE}
brooklyn_man_dinner <- manhattan_matrix("Brooklyn", dinner_time_transport)

heatmap_function(brooklyn_man_dinner)
```

## Queens to Manhattan

```{r ,echo=FALSE, warning=FALSE, message=FALSE}
queens_man_dinner <- manhattan_matrix("Queens", dinner_time_transport)

heatmap_function(queens_man_dinner)
```

## Bronx to Manhattan

```{r ,echo=FALSE, warning=FALSE, message=FALSE}
bronx_man_dinner <- manhattan_matrix("Bronx", dinner_time_transport) 

heatmap_function(bronx_man_dinner)
```


# Late Night 

## Manhattan to Manhattan

```{r ,echo=FALSE, warning=FALSE, message=FALSE}
man_man_late <- manhattan_matrix("Manhattan", late_night_transport)

heatmap_function(man_man_late)
```


## Brooklyn to Manhattan

```{r ,echo=FALSE, warning=FALSE, message=FALSE}
brooklyn_man_late <- manhattan_matrix("Brooklyn", late_night_transport)

heatmap_function(brooklyn_man_late)
```

## Queens to Manhattan

```{r ,echo=FALSE, warning=FALSE, message=FALSE}
queens_man_late <- manhattan_matrix("Queens", late_night_transport)

heatmap_function(queens_man_late)
```

## Bronx to Manhattan

```{r ,echo=FALSE, warning=FALSE, message=FALSE}
bronx_man_late <- manhattan_matrix("Bronx", late_night_transport) 

heatmap_function(bronx_man_late)
```



