---
title: "Taxi Zones"
author: "Adeline Shin"
date: "11/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# install.packages("sf")
# install.packages("tmap")
# install.packages("ggmap")

library(tidyverse)
library(leaflet)
library(viridis)
library(sf)
library(sp)
library(tmap)
library(plotly)
```

# Loading in Data for Taxi Zones
```{r echo = FALSE}
taxi_zones = read.csv("./data/taxi_zones.csv") %>% 
  select(-shape_length, -shape_area)

zone_map_data = read_sf("./data/nyu_2451_36743.shp")
```

# Mapping Dropoffs in Manhattan on Feb 14
```{r echo = FALSE, message = FALSE, warning = FALSE}
taxi_data = 
  read.csv("./data/transport_final.csv")

do_neighborhood_count = as.data.frame(table(taxi_data$do_neiborhood)) %>% 
  select(zone = Var1, freq = Freq)

zone_maps_plot = left_join(zone_map_data, do_neighborhood_count, by = "zone") %>% 
  na.omit() %>% 
  filter(borough == "Manhattan") %>% 
  select(zone, everything())

tmap_mode("view")

zone_map =
  tm_shape(zone_maps_plot) +
  tm_polygons(
    "freq",
    style = "quantile",
    ) +
  tm_layout(title = "Dropoffs in Manhattan on Feb 14", title.size = 0.6, legend.text.size = 0.5, frame = FALSE)

zone_map + 
  tm_basemap(server = "OpenStreetMap")

```

# Doing the same for just Valentine's Day dinner
```{r echo = FALSE, message = FALSE, warning = FALSE}
vday_dinner_data =
  taxi_data %>% 
  separate(pickup_time, into = c("pickup_hr", "pickup_min", "pickup_sec"), sep = ":") %>% 
  separate(dropoff_time, into = c("dropoff_hr", "dropoff_min", "dropoff_sec"), sep = ":") %>% 
  select(-pickup_sec, -pickup_min, -dropoff_sec, -pickup_sec) %>% 
  mutate(
    pickup_hr = as.numeric(pickup_hr),
    dropoff_hr = as.numeric(dropoff_hr)
  ) %>% 
  filter(dropoff_hr == 18 | dropoff_hr == 19 | dropoff_hr == 20)

vday_do_neighborhood_count = as.data.frame(table(vday_dinner_data$do_neiborhood)) %>% 
  select(zone = Var1, freq = Freq)

vday_zone_maps_plot = left_join(zone_map_data, vday_do_neighborhood_count, by = "zone") %>% 
  na.omit() %>% 
  filter(borough == "Manhattan") %>% 
  select(zone, everything())

vday_zone_map =
  tm_shape(vday_zone_maps_plot) +
  tm_polygons(
    "freq",
    style = "quantile",
    ) +
  tm_layout(title = "Valentine's Dinner Dropoffs in Manhattan", title.size = 0.6, legend.text.size = 0.5, frame = FALSE)

vday_zone_map + tm_basemap(server = "OpenStreetMap")
```

# Doing this for cars with only 2 passengers
```{r echo = FALSE, message = FALSE, warning = FALSE}
two_passenger_dinner_data =
  vday_dinner_data %>% 
  filter(passenger_count == 2)

two_pass_dinner_count = as.data.frame(table(two_passenger_dinner_data$do_neiborhood)) %>% 
  select(zone = Var1, freq = Freq)

two_pass_zone_maps_plot = left_join(zone_map_data, two_pass_dinner_count, by = "zone") %>% 
  na.omit() %>% 
  filter(borough == "Manhattan") %>% 
  select(zone, everything())

two_pass_zone_map =
  tm_shape(two_pass_zone_maps_plot) +
  tm_polygons(
    "freq",
    style = "quantile",
    ) +
  tm_layout(title = "Valentine's Dinner Dropoffs (2 Passengers)", title.size = 0.6, legend.text.size = 0.5, frame = FALSE)

two_pass_zone_map + tm_basemap(server = "OpenStreetMap")
```
